# Generated by Django 4.1.2 on 2022-10-31 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], max_length=4)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=64)),
                ('info', models.TextField(default='该用户未设置签名', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('photo', models.ImageField(default='img/default.png', upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
                ('to_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.box')),
            ],
        ),
    ]
