# Generated by Django 4.1.2 on 2022-10-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')]),
        ),
    ]
