# Generated by Django 4.1.2 on 2022-10-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_box_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
