# Generated by Django 4.1.2 on 2022-10-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_box_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='area',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
