# Generated by Django 4.1.2 on 2022-11-02 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_comment_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='box',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='box',
            name='area',
            field=models.CharField(max_length=64, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='box',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='box',
            name='info',
            field=models.TextField(default='该用户未设置签名', null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='box',
            name='phone',
            field=models.CharField(max_length=32, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='box',
            name='real_name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fake_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
