# Generated by Django 4.1.2 on 2022-11-03 02:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_box_time_alter_box_age_alter_box_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PickHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.box')),
                ('picker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user', to_field='fake_name')),
            ],
        ),
    ]
