# Generated by Django 4.1.3 on 2022-12-27 12:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_box_pic_box_school_fold_fold_id_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='free',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
