# Generated by Django 4.1.3 on 2022-12-30 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_box_free_box_photo_box_school_user_email_infcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fold',
            name='fold_id',
            field=models.IntegerField(verbose_name='收藏夹序列号'),
        ),
    ]
